### ISSUE TITLE
WebUI Progress Bar text color

### ISSUE THREAD

**Issue by NLZ** [catppuccin/qbittorrent#31]
Would it be possible to change the Progress Bar's text color on the WebUI?
Currently it's white on the light blue background, making it harsh and off-putting.

Mocha:
![Image](https://github.com/user-attachments/assets/798d90cb-4045-44eb-a0ac-f0b23e34760e)

Maybe black or the background color could work.

**Comment by arminius-smh** [comment]
Unfortunatly, I don't think it's really possible to easily edit that to be consistent for the theme.

The qbittorrent theme for webui uses the theme.park enviornment as a community theme, and they set the font color on the progress bar to `var(--label-text-color)` (which in catppuccin's theme.park theme is `#fff`)
https://github.com/themepark-dev/theme.park/blob/928ef95bbaef193affd1079d45ffa00cd293300c/css/base/qbittorrent/qbittorrent-base.css#L496-L499

As catppuccin is only a theme.park community theme, and this works well with the official themes, it can't be edited more granuarly for the catppuccin theme/every change here would need to not break anything with all the official themes.

The best way if you really want this changed would be to apply the theme manually as a stylus theme and then editing the css, e.g. instead of importing `@import "https://theme-park.dev/css/base/qbittorrent/catppuccin-mocha.css";` in a stylus theme, directly copying the css from the sources and then editing the `color` attribute if the `.progressbar_dark` selector

I do however also think the way it looks right now, still looks the best with the consistent font color across the other values, like name, size etc, even though the contrast may not be perfect since otherwise it isn't as colorful for the different torrent states as the desktop client theme and only consists of the default text color.

Here I already extracted it and changed the background color to `var(--main-bg-color)`, but of course feel free to edit it to any color you like:

![Image](https://github.com/user-attachments/assets/8bba5ef4-e5d0-494f-b134-039ab09186c0)
 
(I also added the changes of https://github.com/themepark-dev/theme.park/commit/ba2b86b2c934f5bd499cf35121de766a49efa93a that are still in theme.park's development branch, but not in stable yet)

<details>

<summary>userstyle.css</summary>

```css
:root {
  --main-bg-color: #1e1e2e;

  --modal-bg-color: #181825;
  --modal-header-color: #11111b;
  --modal-footer-color: #11111b;

  --drop-down-menu-bg: #313244;

  --button-color: #313244;
  --button-color-hover: #45475a;
  --button-text: var(--text);
  --button-text-hover: var(--text-hover);

  --accent-color: 137, 180, 250; /* Mocha Blue */
  --accent-color-hover: rgb(var(--accent-color), 0.8);
  --link-color: var(--text);
  --link-color-hover: #89b4fa;
  --label-text-color: #fff; /* have to break convention here */

  --text: #cdd6f4;
  --text-hover: var(--text);
  --text-muted: a6adc8;

  /* Specials */
  --arr-queue-color: #a6e3a1; /* Servarr apps + Bazarr */
  --plex-poster-unwatched: #fab387;
  --petio-spinner: invert(66%) sepia(15%) saturate(1451%) hue-rotate(185deg) brightness(105%) contrast(96%); /* Made with https://codepen.io/jsm91/embed/ZEEawyZ */ /* Blue */
  --gitea-color-primary-dark-4: var(--accent-color);
  --overseerr-gradient: linear-gradient(
    var(--main-bg-color),
    var(--main-bg-color)
  ); /* Make sure this is compatible with whatever takes in the gradient */
}



::-webkit-input-placeholder{
    color:var(--text-muted)!important
}
:focus::-webkit-input-placeholder{
    color:var(--text-hover)!important
}
:-moz-placeholder{
    color:var(--text-muted)!important
}
:focus:-moz-placeholder{
    color:var(--text-hover)!important
}
::-moz-placeholder{
    color:var(--text-muted)!important
}
:focus::-moz-placeholder{
    color:var(--text-hover)!important
}
:-ms-input-placeholder{
    color:var(--text-muted)!important
}
:focus:-ms-input-placeholder{
    color:var(--text-hover)!important
}
:root{
    --transparency-dark-05:rgba(0, 0, 0, .05);
    --transparency-dark-10:rgba(0, 0, 0, .10);
    --transparency-dark-15:rgba(0, 0, 0, .15);
    --transparency-dark-25:rgba(0, 0, 0, .25);
    --transparency-dark-35:rgba(0, 0, 0, .35);
    --transparency-dark-40:rgba(0, 0, 0, .40);
    --transparency-dark-45:rgba(0, 0, 0, .45);
    --transparency-dark-50:rgba(0, 0, 0, .50);
    --transparency-dark-55:rgba(0, 0, 0, .55);
    --transparency-dark-60:rgba(0, 0, 0, .60);
    --transparency-dark-65:rgba(0, 0, 0, .65);
    --transparency-dark-70:rgba(0, 0, 0, .70);
    --transparency-dark-75:rgba(0, 0, 0, .75);
    --transparency-dark-80:rgba(0, 0, 0, .80);
    --transparency-dark-85:rgba(0, 0, 0, .85);
    --transparency-dark-90:rgba(0, 0, 0, .90);
    --transparency-light-05:rgba(255, 255, 255, .05);
    --transparency-light-10:rgba(255, 255, 255, .10);
    --transparency-light-15:rgba(255, 255, 255, .15);
    --transparency-light-20:rgba(255, 255, 255, .20);
    --transparency-light-25:rgba(255, 255, 255, .25);
    --transparency-light-30:rgba(255, 255, 255, .30);
    --transparency-light-35:rgba(255, 255, 255, .35);
    --transparency-light-45:rgba(255, 255, 255, .45);
    --transparency-light-50:rgba(255, 255, 255, .50);
    --transparency-light-55:rgba(255, 255, 255, .55);
    --transparency-light-95:rgba(255, 255, 255, .95)
}
::-webkit-scrollbar{
    width:10px;
    height:10px
}
::-webkit-scrollbar-corner{
    background:var(--transparency-dark-10)
}
::-webkit-scrollbar-thumb{
    -webkit-border-radius:5px;
    border-radius:5px;
    background:var(--transparency-dark-10)
}
body,html{
    color:var(--text);
    background:0 0
}
body{
    background:var(--main-bg-color);
    background-repeat:repeat,no-repeat;
    background-attachment:fixed,fixed;
    background-position:center center,center center;
    background-size:auto,cover;
    -webkit-background-size:auto,cover;
    -moz-background-size:auto,cover;
    -o-background-size:auto,cover;
    color:var(--text)
}
#desktop{
    background:var(--main-bg-color);
    background-repeat:repeat,no-repeat;
    background-attachment:fixed,fixed;
    background-position:center center,center center;
    background-size:auto,cover;
    -webkit-background-size:auto,cover;
    -moz-background-size:auto,cover;
    -o-background-size:auto,cover
}
input:disabled{
    color:#545454;
    cursor:default;
    background:var(--transparency-light-05)!important;
    border:none!important
}
input[type=text i]{
    color:var(--text-hover);
    background:var(--transparency-dark-25);
    border-width:0;
    outline:0;
    border:none;
    border-radius:3px
}
input[type=password i]{
    color:var(--text-hover);
    background:var(--transparency-dark-25);
    border-width:0;
    outline:0;
    border:none;
    border-radius:3px
}
input[type=number i]{
    color:var(--text-hover);
    background:var(--transparency-dark-25);
    border-width:0;
    outline:0;
    border:none
}
input[type=file i]{
    color:var(--text-hover);
    background:var(--transparency-dark-25);
    border-width:0;
    outline:0;
    border:none
}
input[name=category i]{
    color: var(--text-hover);
    background: var(--transparency-dark-25);
    border-width:0;
    outline:0;
    border:none
}
input[type=file i]{
    border:none
}
select{
    border:none!important
}
.mochaTitlebar h3,a,h2,h3,h4{
    color:var(--text-hover)
}
#main h1{
    display:block;
    font-size:2em;
    margin-block-start:2em;
    margin-block-end:-.9em;
    margin-inline-start:0;
    margin-inline-end:0;
    font-weight:700;
    color:var(--text-hover)
}
#error_msg{
    text-transform:uppercase;
    color:#d8000c;
    background-color:#ffd2d2;
    font-family:Helvetica,Arial,sans-serif;
    left:50%;
    top:20%;
    transform:translate(-50%,-50%);
    -ms-transform:translate(-50%,-50%);
    -webkit-transform:translate(-50%,-50%);
    margin-left:auto;
    margin-right:auto;
    text-align:center;
    position:absolute;
    border-radius:4px
}
#main{
    margin-left:auto;
    margin-right:auto;
    text-align:center;
    position:absolute;
    left:50%;
    top:50%;
    transform:translate(-50%,-50%);
    -ms-transform:translate(-50%,-50%);
    -webkit-transform:translate(-50%,-50%);
    padding-top:0;
    width:400px;
    height:460px;
    -webkit-box-shadow:0 0 10px rgba(0,0,0,.6);
    box-shadow:0 0 10px rgba(0,0,0,.6)
}
#logo img{
    height:11em;
    position:absolute;
    left:50%;
    transform:translate(-50%,-50%);
    -ms-transform:translate(-50%,-50%);
    -webkit-transform:translate(-50%,-160%)
}
#formplace{
    text-transform:uppercase;
    text-align:left;
    font-size:12px;
    font-family:"Helvetica Neue",Helvetica,Arial,sans-serif!important;
    font-weight:300!important;
    padding:10px;
    position:absolute;
    left:50%;
    top:50%;
    transform:translate(-50%,-50%);
    -ms-transform:translate(-50%,-50%);
    -webkit-transform:translate(-50%,-50%)
}
label{
    cursor:default;
    font-family:"Helvetica Neue",Helvetica,Arial,sans-serif!important;
    font-weight:300!important
}
#desktopNavbar{
    background:var(--transparency-dark-25);
    height:20px;
    border-bottom:1px solid transparent
}
#desktopNavbar ul li a{
    color:var(--text);
    padding:1px 10px
}
#desktopNavbar ul li a:hover{
    color:var(--text-hover);
    background:var(--transparency-light-10)
}
#desktopNavbar li ul li a:hover{
    background:var(--transparency-light-10);
    color:var(--text-hover)
}
#desktopNavbar li ul{
    border:1px solid transparent;
    background:var(--modal-bg-color);
    background-repeat:repeat,no-repeat;
    background-attachment:fixed,fixed;
    background-position:center center,center center;
    background-size:auto,cover;
    -webkit-background-size:auto,cover;
    -moz-background-size:auto,cover;
    -o-background-size:auto,cover
}
#desktopNavbar li ul li a{
    color:var(--text)
}
#desktopHeader{
    background:var(--main-bg-color);
    background-repeat:repeat,no-repeat;
    background-attachment:fixed,fixed;
    background-position:center center,center center;
    background-size:auto,cover;
    -webkit-background-size:auto,cover;
    -moz-background-size:auto,cover;
    -o-background-size:auto,cover
}
#desktopFooter{
    background:0 0
}
.dynamicTable th{
    background:var(--transparency-dark-25)!important;
    border-right-color:rgba(255,255,255,.08)!important;
    color:var(--text-hover)
}
.dynamicTable thead tr{
    background-color:transparent!important
}
.dynamicTable thead tr{
    background-color:transparent!important
}
.dynamicTable{
    background:var(--transparency-dark-25)
}
.dynamicTable tbody tr{
    background:var(--transparency-dark-10)!important
}
.dynamicTable tbody tr.alt,.dynamicTable tbody tr:nth-child(2n){
    background:var(--transparency-light-10)!important
}
.dynamicTable tbody tr:hover{
    background:var(--transparency-light-15)!important;
    color:var(--text-hover)
}
.dynamicTable tbody tr.selected{
    background-color:rgba(var(--accent-color),.6)!important;
    color:var(--label-text-color)
}
.panel{
    background:var(--main-bg-color);
    background-repeat:repeat,no-repeat;
    background-attachment:fixed,fixed;
    background-position:center center,center center;
    background-size:auto,cover;
    -webkit-background-size:auto,cover;
    -moz-background-size:auto,cover;
    -o-background-size:auto,cover;
    border-bottom:1px solid transparent
}
#pageWrapper{
    border-top:1px solid transparent;
    border-bottom:1px solid transparent
}
li.divider{
    border-top:1px solid var(--transparency-light-25)!important
}
#main input[type=text i]{
    color:var(--text-hover);
    background:var(--transparency-dark-25);
    border-width:0;
    outline:0;
    border:none;
    border-radius:4px;
    width:250px;
    height:24px;
    padding:7px 12px
}
#main input[type=text i]:focus{
    background:var(--transparency-dark-45)
}
#main input[type=password i]{
    color:var(--text-hover);
    background:var(--transparency-dark-25);
    border-width:0;
    outline:0;
    border:none;
    border-radius:4px;
    width:250px;
    height:24px;
    padding:7px 12px
}
#main input[type=password i]{
    background:var(--transparency-dark-45)
}
#loginform #login{
    padding:6px 15px!important;
    width:100%;
    margin-top:35px;
    background-color:var(--button-color)!important;
    border:none;
    border-radius:4px;
    color:var(--button-text)!important;
    outline:0;
    text-transform:uppercase;
    font-size:18px;
    font-weight:300;
    height:44px;
    line-height:1.3333333
}
#loginform #login:hover{
    background-color:var(--button-color-hover)!important;
    padding:6px 15px;
    border-radius:4px;
    cursor:pointer;
    border:none;
    color:var(--button-text-hover)!important
}
.contextMenu{
    border:1px solid transparent;
    background:var(--modal-bg-color);
    background-repeat:repeat,no-repeat;
    background-attachment:fixed,fixed;
    background-position:center center,center center;
    background-size:auto,cover;
    -webkit-background-size:auto,cover;
    -moz-background-size:auto,cover;
    -o-background-size:auto,cover
}
.contextMenu li a{
    color:var(--text)
}
.contextMenu li a:hover{
    background-color:rgba(255,255,255,.08)!important;
    color:var(--text-hover)
}
.contextMenu li ul{
    border:1px solid transparent;
    background:var(--modal-bg-color);
    background-repeat:repeat,no-repeat;
    background-attachment:fixed,fixed;
    background-position:center center,center center;
    background-size:auto,cover;
    -webkit-background-size:auto,cover;
    -moz-background-size:auto,cover;
    -o-background-size:auto,cover
}
.contextMenu .separator{
    border-top:1px solid var(--transparency-light-10)
}
.selectedFilter{
    background-color:var(--button-color)!important;
    color:var(--button-text)!important
}
.selectedFilter:before{
    color:var(--button-color-hover)!important
}
ul.filterList li:hover{
    background-color:var(--transparency-light-15);
    color:var(--text-hover)!important
}
ul.filterList .selectedFilter:hover{
    background-color:var(--button-color-hover);
    color:var(--button-text-hover)
}
ul.filterList li:hover:before{
    color:var(--button-color-hover)!important
}
.columnHandle{
    background:var(--transparency-dark-45);
    border:1px solid transparent
}
.bottomPanel{
    background:var(--transparency-dark-25)!important
}
#progress{
    border:1px solid var(--transparency-light-25)
}
hr{
    background-color:var(--transparency-light-25);
    color:var(--text)
}
.panel-headerContent.tabs{
    background:0 0!important
}
.panel-header{
    background:var(--transparency-dark-25)!important;
    border-bottom:1px solid transparent!important
}
.horizontalHandle{
    background:0 0!important
}
.tab-menu li.selected a{
    color:rgb(var(--accent-color))!important;
    background:0 0!important;
    font-weight:400!important
}
.tab-menu li a{
    color:var(--text)!important;
    background:0 0!important
}
.tab-menu li.selected{
    background:0 0!important
}
.tab-menu li{
    background:0 0!important
}
.tab-menu li a:hover{
    color:rgb(var(--accent-color))!important
}
.toolbarTabs{
    background:var(--transparency-dark-25)!important;
    margin:0 5px 0 0!important
}
.progressbar_dark{
    background:rgb(var(--accent-color))!important;
    color:var(--main-bg-color) !important;
}
.progressbar_light{
    background:var(--transparency-dark-25)!important;
    color:var(--text-hover)!important
}
.progressbar_wrapper{
    border:1px solid transparent!important
}
.stateIcon{
    background-image:red!important
}
fieldset{
    border-width:1px!important;
    border-style:solid!important;
    border-color:var(--transparency-light-25)!important
}

.mocha {
    background: var(--drop-down-menu-bg);
}

.mochaOverlay{
    position:absolute;
    top:0;
    left:0;
    background:var(--modal-bg-color);
    background-repeat:repeat,no-repeat;
    background-attachment:fixed,fixed;
    background-position:center center,center center;
    background-size:auto,cover;
    -webkit-background-size:auto,cover;
    -moz-background-size:auto,cover;
    -o-background-size:auto,cover;
    border-radius: 0px;
}
.mochaToolbarWrapper{
    width:100%;
    position:relative;
    height:29px;
    background:var(--transparency-dark-25)!important;
    overflow:hidden;
    border-top:none!important
}
.mochaToolbar{
    width:100%;
    border-top:none!important
}
.mochaContentBorder{
    border-top:1px solid var(--transparency-light-25)!important;
    border-bottom:1px solid var(--transparency-light-25)!important
}
.mocha.isFocused .mochaTitlebar h3{
    color:var(--text-hover)
}
fieldset.settings legend{
    color:var(--text-hover)
}
.mochaContentWrapper{
    font-size:12px;
    overflow:auto;
    background:0 0!important
}
fieldset.settings{
    border:solid 1px var(--transparency-light-25)!important;
    border-radius:8px;
    -webkit-border-radius:8px;
    -moz-border-radius:8px;
    padding:4px 4px 4px 10px
}
textarea:disabled{
    color:var(--text-muted);
    cursor:default;
    background:var(--transparency-light-05)!important;
    border:none!important
}
textarea{
    color:var(--text-hover)!important;
    cursor:default;
    background:var(--transparency-dark-25)!important;
    border:none!important
}
#watched_folders_tab td,#watched_folders_tab th{
    padding:2px 4px;
    border:1px solid var(--transparency-light-25)!important
}
input[type=button i]:hover{
    background-color:var(--button-color-hover);
    padding:6px 15px;
    cursor:pointer;
    border:none;
    color:var(--button-text)
}
input[type=button i]{
    padding:6px 15px!important;
    background-color:var(--button-color);
    cursor:pointer;
    border:none;
    color:var(--button-text)
}
button{
    background-color:var(--button-color)!important;
    cursor:pointer;
    border:2px solid transparent;
    color:var(--button-text)
}
button:hover{
    background-color:var(--button-color-hover)!important;
    cursor:pointer;
    border:2px solid transparent;
    color:var(--button-text)
}
input[type=submit i]{
    padding:6px 15px!important;
    width:100%;
    margin-top:15px;
    background-color:var(--button-color)!important;
    border:none;
    color:var(--button-text);
    outline:0;
    text-transform:uppercase
}
input[type=submit i]:hover{
    padding:6px 15px!important;
    background-color:var(--button-color-hover)!important;
    width:100%;
    cursor:pointer;
    border:none;
    color:var(--button-text);
    outline:0;
    text-transform:uppercase
}
#contextCategoryList,.contextMenu{
    box-shadow:0 8px 16px 0 rgba(0,0,0,.2),0 6px 20px 0 rgba(0,0,0,.19)
}
select{
    background:var(--transparency-dark-25);
    color:var(--text)
}
select:focus{
    background:var(--drop-down-menu-bg);
    color:var(--text)
}
.select-watched-folder-editable{
    background-color:var(--transparency-dark-05);
    border:solid var(--transparency-light-10) 1px
}
#torrentsFilterToolbar{
    float:right;
    margin-right:.5rem
}
#torrentsFilterInput {
    background: var(--transparency-dark-25);
    border: none;
}
label[for="torrentsFilterRegexBox"] {
      border: none !important;
}
```

</details>

If you're curious why there only is a theme.park theme/why it's a bit more convoluted to edit, it's because qbit doesn't allow the loading of additional css, but only allows the exchange of a complete frontend, 
which theme.park solves by executing a script that clones the qbit frontend for the selected version and then edits the html to include the import statement I mentioned at the beginning.
