### ISSUE TITLE
Support webUI

### ISSUE THREAD

**Issue by alexsalex** [catppuccin/qbittorrent#6]
subj

**Comment by sgoudham** [comment]
> Though I do have to note that setting up currently difficult and requires either a webserver, or github pages.

It's worth mentioning that Catppuccin has been upstreamed as a community theme on theme.park, which I think should resolve the need for a webserver or GitHub pages here.

**Comment by iwa** [comment]
still feels like a lot of troubles just to install a theme on Qbit... I personally don't care at all theming my other apps, so it feels like an unnecessary overhead just for a Qbit theme :/

**Comment by sgoudham** [comment]
> still feels like a lot of troubles just to install a theme on Qbit... I personally don't care at all theming my other apps, so it feels like an unnecessary overhead just for a Qbit theme :/

Including a theme for the WebUI seems like it introduces a high maintenance burden (from looking at other themes) that I'm personally not interested in adding support for it.

It'd be nice if someone could confirm that a theme can be used via `theme.park` as mentioned above.

**Comment by arminius-smh** [comment]
![qbitweb-catppuccin-mocha](https://github.com/user-attachments/assets/4e229e8f-1ac7-424b-8164-f410f1dde78a)

This is qbit web with catppuccin-mocha from theme.park for v4.6.5
running qbit in a docker container from linuxserver, it can also be installed with just these env variables:
```
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.5
    environment:
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - QBITTORRENT_VERSION=4.6.5
      - TP_COMMUNITY_THEME=true
      - TP_THEME=catppuccin-mocha
```

alternatively, it can also be easily installed via stylus, just add this to a new style:

```
@import "https://theme-park.dev/css/base/qbittorrent/catppuccin-mocha.css";
```

no need to self host anything or use github pages
